#+SETUPFILE: org-templates/level-0.org
#+TITLE:     Pallet - Release Notes
#+DESCRIPTION: Release notes for pallet releases
#+KEYWORDS: pallet palletops contribute

The latest release is 0.6.4.


* 0.6.4
** Fixes
- Fix the automatic addition of :configure to the converge phase-list
  :configure was not being added if another phase was specified

* 0.6.3
** Features
- Allow specification of a cookie in wait-for-http-status

- Add script.lib/selinux-bool to setsebool values
  The script guards the setsebool call with a check for an active selinux
  configuration.

- Add dirname script to pallet.script.lib

- Add :insecure option to lib/download-file and expose in remote-file
  It is useful to be able to ignore ssl certificates that do not validate

- Add a retry action
  `retry-until` repeats until a condition is true, or a maximum number of
  retries is reached.

- Add :if-stopped option to service action

- Add images to ComputeService protocol

- Add plugable error handling
  Adds the :execute-status-fn algorithm to the environment, which controls
  wether an error stops processing on a node. Adds the raise-on-error
  middleware, for raising an execption when an error occurs running a phase
  on a node

- Updates to allow pallet-task to take an :environment keyword arg.
  Updated pallet-task to allow additional keyword args (source compatible).
  Also updated converge/converge_cluster/destroy_cluster/lift tasks to
  accept (and prefer) the explicitly passed environment. If none is given,
  they fall back to looking for an :environment key in the project, as
  before.

- Allow explicit passing of initial build phases in live-test

- Ignore invalid ssl for jpackage utils download from github

- Add a get-target-settings overload for specifying default value

- Add with-ssh-tunnel macro.
  Allows for performing actions on remote nodes from clojure on the pallet machine.

- Add ImageManager protocol to vmfest provider

- Add vmfest/has-image?
  Enable checking for the presence of a specific vmfest image

- Add publish-image to vmfest provider

- Add vmfest task
  Allow the running of scripts to set up local vmfest environments

- Add a task to list images

- Switch to tools.logging and logback via slf4j

- Upgrade to latest clj-ssh

- Upgrade to latest pallet-common

- Upgrade to latest parent pom

- Upgrade to stevedore 0.7.0


** Fixes

- Update logging of errors
  Ensure only the error message is logged, not the whole result

- Add logging of all errors from running a phase

- Fix script hostname function for the case with no arguments

- Fix rsync to use the admin user defined in the session
  The rsync action was using the global admin-user

- Cleanup plan-for-server environment merge expression

- Add other node-spec keys to vmfest template matching

- Add warning on port forwading failure

- Add test for delayed argument evaluation in action plan

- Work around tools.logging bug with non-literal format strings

- Set namespace for vmfest-script

- Fix :if-flag in action.service/service and and init-script-path

- Fix major leak of ssh connections

- Check remote md5 before transferring local files
  To prevent multiple uploads of unchanged local content when using
  remote-file with a :local-file source, add a comparison of the local
  content md5 with the remote-file's md5

- Use nodes from the :node-set to compute :all-nodes
  When no compute service is available, take :all-nodes from the nodes
  specified in :node-set

- Ensure all exceptions from actions are caught
  When executing actions, ensure unexpected exceptions are caught for
  handling in the middleware pipeline.

- Add check for /etc/selinux to selinux-file-type script function
  Try harder to determine whether the target is selinux capable

- Make jsch use daemon threads
  jsch seems to be leaking threads, which prevented a clean shutdown of
  lein tasks.

* 0.6.2
** Features
- Add settings functions to parameters
  In order to simplify the use of the :settings phase, adds
  assoc-target-settings, update-target-settings, get-target-settings and
  get-node-settings.

- Add canonical-path and selinux-file-type to script.lib

- Enable :local-file and remote-file options in action.remote-directory
  Also adds an :unpack :jar option

** Fixes
- Fixed the closing parentheses at the end of pallet.core/group-spec example

- Ensure environment from group-spec is evaluated if required

- Cache the value of pallet version

- Improve clarity of converge-cluster/build-args

- Be more aggressive about forcing futures

- Fix remote-file with :blob source

* 0.6.1
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes

- Identify script output with server address
  In order to provide clear provenance of script output when executing with
  parallel phases, we attach the server address

- Use hard links for md5 temporary checks
  The symbolic link ended up pointing to the wrong location

- Add normalisation of downloaded md5 files
  Normalise downloaded md5 files to include the filename to verify, as used
  by ubuntu md5sum.

- Fix parallel phase execution
  Need to ensure all futures are generated before any deref.

- Fix md5sum-verify to avoid leaving the caller in a different directory

- Fix recursive setting of ownership in directory and remote-directory

- Add ability to single quote script.lib/sed-file expressions

- Fix package manager specific filesystem paths

- Fix action.user/user :group option for ubuntu, etc

- Fix :enable option for pallet.action.service/service

- Ensure groups are set up before users in pallet.action.user

- Fix lib/sed-file for string experession with no restriction

* 0.6.0
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Features

Update to jclouds 1.0.0.

* 0.5.1
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Features
- Add core/destroy-cluster and destroy-cluster task

- Add converge-cluster task

- Update pallet.action.user/user to handle login group
  :group can be passed a group name to set the login group.

  :groups now accepts a sequence of group names.

  usermod now specialised on rh derivatives.

- Add pallet.script.lib/has-command? to check availablity of command on path
  Uses hash, instead of checking with which.  This is a lighter weight,
  builtin, so is more portable. Some which's apparently always return a
  zero status too.

  download-file and pallet.crate.network-service are updated to use this.

- Add :node-set-selector option to pallet.core
  Add the ability to partition the nodes for lifting, based on a function
  passed as an option. Currently implemented partitioning functions are
  core/all-node-set-selector and core/new-node-set-selector.

- Change default environment merge to deep-merge
  User defined keys are deep merged by default, to allow them to be built
  from cluster and lift/converge environments.

- Add core/converge-cluster and lift-cluster
  Add's the ability to lift or converge one or more clusters.  Environment
  specified on the cluster-spec is propogated to its groups.

- Automatically run the :settings phase on lift or converge
  In order to allow easy access to configuration metadata, run the
  :settings phase before each lift or converge. The settings phase is
  intended to be non side-affecting.

- Add core/cluster-spec and add roles to server-spec and group-spec
  Allows specification of a cluster made up of heterogeneous groups.  Roles
  allow the cluster to be queried for nodes providing specified roles,
  using session/groups-with-role and session/nodes-with-role

- Add overload for etc-init to /etc/rc.d on arch

- Add support for pacman-db-upgrade in package/minimal-packages

- Add base-distribution to compute and session
  Enable uniform treatment of all derived distributions. E.g. fedora,
  centos, rhel are all based on rh.

- Add debian squeeze to live test images

- Add pallet.test.session-type for vbox headless/gui selection
  When debugging boot issues, it is useful to be able to see the console

- Add action/environmnet for controlling environment variables
  Adds an environment/system-environment that is used to write
  /etc/environment on debian based distros, and /etc/profile.d/xx on redhat
  based distros

- Add ~/.pallet/services/* as a source of service configuration
  In order to allow the distribution of service defintions, enable service
  definition in files in ~/.pallet/services. Add an 'add-service' task that
  can be used to create service definitions from the command line.

- Add support for post beta-9c jclouds snapshot
  HardwareImpl, ImageImpl and NodeMetadataImpl all gain an extra tags
  argument in their constructors

- Add remote-exec, and streaming of output for sh-script

- Add ability to not use a pty for ssh on fedora
  Fedora seems to drop a few characters at the start of an ssh shell
  connection when run with a pty.

  Add an option map to execute/remote-sudo-cmd arguments. Allow
  specification of whether to use a pty or not.

- Allow dependecies between action calls
  In order to have fine grained control over execution order, allow the
  specification of :always-before and :always-after on an action
  definition, and the specification of :always-before and :always-after and
  an :action-id on the action call (via the with-precedence macro).

- Add a :rh image list to live-test
  Provides a means for testing across redhat variants.

- Add fedora support
  Add script function specialisations for fedora, and add fedora 14 to live
  tests

- Allow specification of precedence on an action invocation
  In order to override default precedence rules, allow specification of
  precedence on an action call.

- Add merging of :environment from cake/*project*
  In order to provide an identical environment under a cake task and from a
  cake repl or swank server, merge :environment from cake/*project* in
  compute-service-from-config and compute-service-from-settings

** Fixes and Improvements
- Fix a race in shutting down vmfest nodes

- Improved pallet.execute logging, and checking of blank server address

- Include exception message when provider fails to load

- Fix network-service to use ~lib/exit

- Remove use of pty on arch bootstrap for vmfest

- Add warning for failed require of compute provider

- Fix package/minimal-packages for new stevedore script convention

- Change package/add-rpm to be non-aggregated
  Allow use of rpm-bin in more general situations. Execution sequence can
  now be controlled via with-precedence.

- Modify log message for os-family computed from template

- Add default installonlypkgs list for yum
  When specifying installonlypkgs, the defaults should be added back in
  (these include the kernel packages).

- Fix script.lib/user-home for os-x

- Disable package repos before enabling package repos
  In yum package commands, disable repos before enabling, to allow
  disabling all repos, then explicitly enabling a list

- Fix merge of group specific environment on converge of new nodes

- Fix use of :tag in pallet.environment/session-with-environment

- Remove deprecation warning in vmfest

- Add backward compatability to vmfest for group-name as tag

- Fix vmfest 64bit and os-family detection

- Fix for fedora to use yum


* 0.5.0
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Features

- Switch to release versions of pallet-common and stevedore

- Factor out thread-expr, stevedore and pallet-common

- Conj-ing identity onto the comprehension is unnecessary, as reduce simply
  returns the original value (arg, in this case) if handed an empty list.

- More efficient implementation of for->, without the need to call reverse on
  the list comprehension.
  we now reduce with an initial value of arg and the #(%2 %1) function
  -- (reduce #(%2 %1) arg function-sequence) ends up acting exactly like a
  call to comp with a reversed sequence.

- Update to pallet-pom 0.4.3

- Seperate repository manipulation actions into separate namespaces

- Update to jclouds beta-9c

- Add pallet.stevedore/empty?
  This expands to the -z test.

- Fix log messages for apply-phase

- Fix incorrect switch of phase to task

- Add outputput of partial results from ssh command
  In order to improve the feedback of commands running over ssh, log output
  as it becomes available

- Deprecate pallet.target
  Replaced with pallet.compute/admin-group and pallet.session/admin-group

- Make deprecation messages consistent, and add :deprecated metadata

- Rename request to session. pallet.request-map becomes pallet.session.

- Rename pallet.resource.* to pallet.action.*
  Rename resource to action. Set up forwarding from the pallet.resource
  names.

  pallet.resource.network-service becomes the first core crate at
  pallet.crate.network-service.

  pallet.resoruce.format becomes the first core configuration file
  formatter at pallet.config-file.format.

  pallet.resource.resource-when is renamed pallet.action.conditional

- Refactor script fns into pallet.script.lib and make script fns use unquote
  In order to remove the possibility of accidentally using a script
  function, they must now be invoked using unquote. The use of unquote is a
  reminder that clojure namespace resolution is in effect:
     (stevedore/script (~lib/rm file))

  The script functions have been factored out of pallet.resource.* into
  pallet.script.lib in order to improve the seperation of the target script
  generation.

- Add tests for pallet.phase, fix issues, update compatability

- Add pallet.resource as a compatability namespace

- Refactored execution of actions to allow partial override by middleware
  Allow middleware to override executor functions for specific :action-type
  and :location combinations

- Change resource to action and simplify code
  To make the code clear pallet.resource is refactored into pallet.action,
  pallet.action-plan, and pallet.phase.

  The action-plan can now handle nested scopes.

  The action creation macros have been renamed, and new macros for defining
  unnamed actions are introduced.

  - resource/defresource     action/action
  - resource/defresource     action/def-bash-action
  - resource/defaggregated   action/def-aggregated-action

  For testing, test-utils/build-resources is replaced by
  build-actions/build-actions.

- Fix naming that should refer to group-set rather than node-set

- Add :qos to node-spec to allow quality of service options
  Allows the grouping of template options for quality of service related
  options such as spot price or enabling monitoring

- Add pallet.compute/service as the preferred compute service instantiation
  function
  Provides a single function to access the different compute service
  instantiation functions in pallet.

- Switch environment to use :groups, and deprecate :tags

- Add blobstore mapping for changed jclouds provider names

- Keep track of futures started by pallet
  It is useful to be able to control the futures started by pallet for node
  count adjustments and for executing phases, e.g. to cancel pending
  operations, etc.

- Fix node-spec mapping for converge with multiple targets

- Use symbolic names for vmfest extradata tags

- Remove request from pallet.compute.ComputeService interface

- Change default to parallel lift and converge

- Switch to pallet-pom 0.4.1 and enlive 1.0

- Update to jclouds 1.0-beta-9b

- Introduced group-spec and server-spec
  Refactored to separate domain concepts for group-spec and server-spec.
  Renamed group-node to server.

- Refactored lift* and converge*
  Ensure that all functions called in lift*, converge*, and lift-nodes
  follow the request map state pattern.

- Refactor pallet.core
  Improve naming consistency and reduce complexity of processing the input
  node-set.

  To improve encapsulation of the request map when accessed in crates
  pallet.request-map has been extended to cover a couple of missing
  functions, and some template functions have been altered to take a
  request map rather than a node-spec.

  This changes the keys in the request map used to specify the current
  target.

  Added a top level node-spec function for creating node spec's (to replace
  make-node eventually).

  An effort has been made to preserve backward compatability.

- Unified scriptfn optional args to be keyword argument pairs

- namespaced lookup of first element of a form in a stevedore script expression

  This makes script functions behave similarly to ordinary clojure functions
  and methods.  The first element of a form now has to resolve to a script
  function, unless it is a string or a keyword implemented by pallet.stevedore.

      (file/rm ~path :force true)
      ("rm" -f ~path)



* 0.4.18
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Changes

- Ensure :target-packager is removed after producing resources
  The :target-packager key is not overwritten if it exists, so needs to be
  removed after every node in order for it to be set correctly when using
  nodes with mixed os's.

* 0.4.17
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Changes
- More efficient implementation of for->, without the need to call reverse on
  the list comprehension.
  we now reduce with an initial value of arg and the #(%2 %1) function
  -- (reduce #(%2 %1) arg function-sequence) ends up acting exactly like a
  call to comp with a reversed sequence.

  Conj-ing identity onto the comprehension is unnecessary, as reduce simply
  returns the original value (arg, in this case) if handed an empty list.

- Add a package-manager-option for installonlypkgs on yum
  installonlypkgs allows a list of packages that should be installed,
  rather than upgraded (i.e. old versions are not removed)

- Add functions to access and manipulate the images list in live-test
  In order to allow users of live-test to add their own image lists,
  provide pallet.live-test/add-image-list./start-release.sh 0.4.15 0.4.16
  For this to work, the images to be used can not be bound at compile time,
  so the pallet.live-test/images function is added.

* 0.4.16
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Changes
- Improve robustness of classpath discovery in presence of corrupt jars
  If a jar on the classpath can not be read for some reason, we should not
  give up, but just ignore that jar file

- Ensure all output is read when an ssh shell closes

- Provide better control of ssh ouput reading
  Move to clj-ssh 0.2.4, which provides a larger default piped stream
  buffer (and allows override of the buffer size).

  Allow override of ssh output buffer size with an atom
  (pallet.execute/ssh-output-buffer-size).

  Allow override of ssh output polling period with an atom
  (pallet.execute/ssh-output-poll-period).

- Fix a bug that would cause Pallet to not find compute service in
  config.clj when invoked through lein or cake


* 0.4.15
** Known issues
- Pallet can not find compute service in config.clj when invoked through lein or cake
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].


** Changes
- Update jpackage functions to use jpackage-utils-compat-el5-0.0.1-1
  Add a compatability package to allow jpackge to work with its own
  jpackage-utils

- Add pallet.package/add-rpm to install rpm files

- Add :disable option update-package-list for yum
  Allow for specification of exactly which repos will be updated.

  The log message now also includes the options passed to package-manager

- Add pallet.thread-arg/arg-> for exposing the threaded argument

* 0.4.14
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].


** Changes
- Add logging of unexpected exceptions in pallet-task

- Alter logging format for ssh output to prepend newline
  The incremental ssh output was difficult to read without a leading
  newline

- Add output of partial results from ssh command
  In order to improve the feedback of commands running over ssh, log output
  as it becomes available

- Change pre and after phase names to be namespaced
  To prevent collisions between the pre and after phase names with user
  defined phase names, make the pre and after phase names namespaced with
  pallet.resource

- Rerun phase function after the pre and main phases
  In order for the parameters from running the pre phase to be available in
  the main phase, call the phase function again after executing the
  pre-phase. Similarly for the main-phase and the after-phase

- Update to clj-ssh 0.2.3

- add-jpackage sets the jpackage repos to disabled by default
  Add the jpackage repo list to the :jpackage-repos target parameters. Add
  package-manager-update-jpackage to update the jpackage repos.

- Updated implementation of for->, with support for destructuring.
  The existing implementation of for-> supported the binding of a single
  variable to a single sequence. The updated implementation here makes use
  of clojure.core/for to build up a sequence of functions;
  ((apply comp functionseq) arg) is then used to thread the argument among
  the sequences. Each item in the resulting sequence is dealt with in
  order.

- Update pallet.resource.filesystem/mount to check if a filesystem is mounted
  before attempting to mount it again. Also update it to accept an :fs-type
  arg to set the filesystem type. Updated and added unit tests.

** Fixes

- Ensure pallet.config/service is used if no service specified on command
  line

- Ensure :configure is called for lift if invoked with no phases

- Fix pallet.stevedore unquote splicing of empty sequences

- Update pallet.thread-expr/for-> to handle multiple body forms and empty
  sequences

- Add resource for the pallet version via pallet.core/version



* 0.4.13
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes
- Fix issues with cross-node configuration
  When using delayed arguments or the post phase, to access parameters set
  in a phase, there were several issues that masked the parameters. This
  also adds tests for these use cases.
* 0.4.12
** Known issues
- has an issue with propogation of parameters between phases.
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes
- Build and execute phases one by one
  Fix a regression that prevented execution time additions to parameters
  from being propogated to the next phase. This re-enables use case such as
  ssh-key/record-key

- Add exclusion of log4j.xml from jar (was in pallet-pom)

* 0.4.11
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes
- Pass any :environment key in project.clj to the converge and lif tasks
  In order to allow environment definitions in project.clj, and to enable
  environments to be supplied by the cake context feature, the :environment
  key values from project.clj are passed to the converge and lift commands
  invoked by the converge and lift tasks (used by the lein and cake
  plugins)

- Add logging of pallet version
  To ease identification of pallet versions in the log files, add debug
  level logging of the pallet version on every lift and converge

- Fix loading of providers to work with custom classloaders
  Custom classloaders as used by cake, tomcat, etc, would break the loading
  of the pallet compute providers.

  Fixes #57

- Add an exclusion of clojure to the enlive dependency

* 0.4.10
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes
- Switch from jclouds/node-tag (removed in beta 9), and fix use of
  :environment at the service level

* 0.4.9
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes

- Filter for running nodes in compute/run-nodes for jclouds
  In order to work around an issue 501 in jclouds, the return value of
  org.jclouds.compute/run-nodes is now filtered for running nodes.  This
  should prevent the occasional hang, where pallet would try to ssh into a
  terminated node.

- Switch to pallet-pom 0.4.1 and enlive 1.0

* 0.4.8
** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes

- Use the node image spec to construct the virtualbox machine definition
  In order to allow control of the vmfest hardware and network
  configuration, use the image template to overide the vmfest defaults. At
  present it uses
  :min-cores, :min-ram and :bridged-network.

- Add release scripts

- Fix the lookup of symbols in the :algorithms key of the nvironment
  When evaluating an environment, say from config.clj, then the values
  under the
  :arguments key should be resolved to vars.

- map-to-arg-string: quote arguments
  Handle arguments with spaces like:
  (pallet.resource.user/user "nexus" :comment "Sonatype Nexus system user")

* 0.4.7

** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes

- Documentation fixes for provider dependencies and :services

- Make core/parallel-adjust-node-counts public

- Make compute/vmfest use the :sudo-password option for the user

* 0.4.6

** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Enhancements

- Add a :proxy entry to the environment for specifying a proxy for use by
  remote-file
  When running in environments that have a proxy available, specifying the
  :proxy key of the environment as a url string will allow remote-file to
  use the proxy.

      :environment {:proxy "http://192.168.2.37:3128"}

* 0.4.5

** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Enhancements

- Add a parallel converge, and a lift that applies phases in series,
  and nodes in parallel.

- Make identical node creation parallel in vmfest

- Use environment to select converge and lift algorithms
  Allow selection of parallel or serial execution using the environment.
  The keys used are:
  - [:algorithms :lift-fn]
  - [:algorithms :converge-fn]
  - [:algorithms :vmfest :create-nodes-fn]

  The choice of :converge-fn functions:
  - pallet.core/serial-adjust-node-counts
  - pallet.core/parallel-adjust-node-counts

  The choice of :lift-fn functions:
  - pallet.core/sequential-lift
  - pallet.core/parallel-lift

  The choice of :create-nodes functions:
  - pallet.compute.vmfest/serial-create-nodes
  - pallet.core/parallel-create-nodes

- Add parallel execution of live-tests
  Parallel execution is off by default. It can be enabled with the
  pallet.live-test.parallel system property.  Live tests need to
  pallet.live-test/test-for to enable this.


* 0.4.4

** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Enhancements
- Add an environment concept
  The environment concept allows passing of external data to pallet, and
  allows project, service, or command line overrides of pallet algorithms
  and domain data objects.

  The :environment key is recognised by lift and converge, in the
  config.clj file at the global and service scope. A project specific
  environment maybe be specified in pallet.config/environment.

* 0.4.3

** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Fixes

- Remove extra keys from request in converge and lift tasks

  lein and cake plugins were triggering the new keyword argument checking in
  lift and converge

* 0.4.2

** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Enhancements

- Speeds up creating and destroying virtualbox vms using vmfest.

  Replace use of manager/as-map in pallet/compute/vmfest.clj with faster
  alternative


* 0.4.1

** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** Enhancements

- This targets vmfest 0.2.1, adding support for virtualbox 4.0.2.

- Adds handling of inaccessible virtual box machines

** Fixes

- Fixes handling of the case where a new machine fails to get an IP address
  assigned

* 0.4.0

** Install

The release is on [[http://oss.sonatype.org/content/repositories/releases/org/cloudhoist/pallet][sonatype]].

** General

The pallet crates have been moved into the pallet-crates project.

This release introduces the ~/.pallet/config.clj configuration file.

maven-settings is now an optional dependency. This means that to use
settings.xml to store pallet configuration, you need to add
org.apache.maven/maven-settings 2.0.10 to your project dependencies. This
dependency was causing conflicts with lein.

There is also preliminary support for virtualbox via vmfest.



** Lein and cake
- Fix reporting of unexpected error stack traces in pallet.main

- Fix pallet.main/report-unexpected-exception, and add test for it


** Fixes

- Fix bug in pallet.script/add-to-scripts
  The add-to-scripts function was referencing *scripts*, which was
  incorrect since it is called by an alter-var-root invoctation on
  *scripts*.

  Change pallet.scripts/*scripts* to pallet.script/scripts, and make it an atom

  Added extra tests and logging around script template selection for
  generation of the bootstrap script.

  Added a condition/raise when jclouds returns OsFamily/UNRECOGNISED on the
  image to be used for a new node.

- Improve exception message in stevedore/emit-infix

- Fix md5-verify script implementation on ubuntu
- Use --status for md5sum-verify on debian

- Add repositories to pom to make sure parent pom can be found

- Fix option argument processing for add-epel

- Ensure package-source is executed before either package-manager or package

- fix pallet.template/path-components for windows

- Add test for propogation of :parameters supplied to lift

- Remove the -n option for sudo on debian

- Fix execute/remote-sudo

- Fix a bug that prevented converge from reducing an existing node count to a
  smaller, non-zero number of nodes

- Remove -n option in sudo-no-password for mac

- Fix jpackage-utils install priority. Remove duplicate package requests

- Remove superfluous spaces produced by stevedore/script

- Ensure correct treatment in stevedore for single statement if blocks
  containing newlines

- Correct quoting of checked-commands failure message

- Allow pallet-version to be nil, to solve issue when compiling before
  resource generation

- Fix pacmans purge test

- purge-package (pacman): also remove all (possibly modified) config files

- Fix forwaring of all provider options from config, and ensure that provider
  specific jclouds endpoint option is used

- Fix pallet.thread-expr/if-> for case with no else expression

- fix infinite recursion when pallet.main is invoked without command line
  arguments


** Enhancements

- Add a timeout to vmfest/wait-for-ip

- Make minimal-packages update coreutils and sudo on ubuntu
- Fix pallet.resource.package/minimal-packages

- Shortcut execution of empty phases

- Add pallet.resource.network-service/wait-for-port-response
  wait-for-port-response is a function to wait for a port to a return a
  response matching a given regex when sent a specific message.

- Add checking of argument keywords to lift and converge

- Add add-debian-backports to pallet.resource.package and process :enable
  options in adjust-packages for aptitude

- Add :proxy option to pallet.resource.file/download-file

- Add the ability to configure the package manager
  Add :configure option to pallet.resource.package/package-manager. The
  only option at the moment is :proxy, which accepts a url for the http
  proxy that should be used by the package manager

- Add :upgrade action to pallet.resource.package/package-manager
  In order to upgrade all installed packages, the :upgrade action is now
  accepted by pallet.resource.package/package-manager. This is implemented
  via the upgrade-all-packages script function.

- Added pallet.live-test for running tests with actual nodes

  Add pallet.test.image-list to select images to use for testing
  When running the live tests, it is useful to be able to specify which
  images to use.  The pallet.test.image-list can be used to specify this.
  The list of images is made available to the tests in
  pallet.live-test/*images*.  The pallet.live-test/exclude-images and
  pallet.live-test/filter-images can be used to special case tests, or
  filter unsupported images.

- Add pallet.resource.network-service with functions for waiting on the state
  of network services

- Add alias as a special form in stevedore
  Use alias to define command aliases:
   (script (alias ls (ls -l)))

- Add pallet.debug with print-request and log-request.
  Add initial helper functions for debugging. print-request and log-request
  can be inserted into a crate to show the intermediate request map.

- Add the form causing an invalid request map to condition message in
  pallet.resource/phase.
  In order to help debugging, when an invalid request map is detected in a
  phase, a condition is raised and the form that returned the invalid map
  will be included in the condition's message.

- Add the :endpoint option to compute/compute-service-from-map.

- List packages after install/remove.
  Ensure feedback on the state of packages after each package operation.

- Add simple validation of the the request map to resource/phase

- Add :no-sudo to the image specification, increase standoff while waiting
  for ip

- Add an :add-scope action to pallet.resource.package/package-manager that
  can be used with debian or ubuntu

- Add compile and tests phase executions for clojure-maven-plugin

- Add marginalia and autodoc output directory targets

- Change jclouds service implementation to use a provider specifc default
  extension list, which will try to use pallet's no-op ssh client for the
  stub service

- Change compute-service-from-map so that the :extensions and :node-list key
  values are read using read-string only when the values are strings

- Add an overload to find-var-with-require for a single namespace qualified
  symbol argument

- Update pallet.main/-main to factor out pallet-task.
  pallet-task returns an integer suitable for System/exit, but never calls
  System/exit.  This simplifies lein interactive and cake integration.

- make package/add-rpmforge an aggregate resource :always-before
  package-manager

- Add pkg- prefixed path functions, for locations of files managed by the
  package manager Package managers such as brew do not install files in the
  base system locations

- Add pallet.thread-expr/let-with-arg-> to allow a let in the middle of a
  threaded expression In pallet crates, it is often useful to access an
  element of the request in the middle of a threaded expression, and
  let-with-arg-> provides access to the request, and allows you to make
  lexical scoped assignments.

- Add per package enabling/disabling of repositories (yum only) Package
  operations are grouped by enabled/disabled repositories and are ordererd
  by a priority

- add pallet.execute/local-checked-script

- Add pallet.core/version based on a maven filtered resource

- Allow documentation string and metadata on pallet.script/defscript
  definitions

- Do not complain about pallet.script/*template* being unbound until trying
  to use a defined script multimethod

- Use (seq *template*) for appropriate logging output of script template

- Make maven-settings an optional dependency This means that to use
  settings.xml to store pallet configuration, you need to add
  org.apache.maven/maven-settings 2.0.10 to your project dependencies. This
  dependency was causing conflicts with lein.

- Add the vmfest compute provider from the vmfest branch

- Update remote-sudo to use the user :password if present, and to use
  sudo-cmd-for to generate the sudo command prefix.

- Improve robustness of stevedore statement generation

- Add :services key for config.clj and deprecate :providers

- Add pallet.resource.format/name-values for formatting name value pairs

- Attempt to use wget if curl not available

- stop ls complaining about no version files when limiting the number of
  versions of a file

- Add pallet.parameter/get-for-service

- Add execute/local-script for running local shell script commands

- Add stevedore/directory?

- Add warn-on-undefined-phase to warn if requested phase is not defined on
  any target tag. Fixes #43

- Explicitly remove :blobstore from jclouds compute service options

- Simplify nodes-in-tag to not rely on the target node

- Make package/add-epel aggregated and force it before any package-manager
  commands

- Allow specification of node-list nodes as data vectors

- Remove default usage of compute provider as blob provider.

- Add :endpoint to config.clj, and pallet.endpoint to settings.xml

- Updates for new repository location. Removal of superfluous config in pom
  (supplied by pallet-pom).

- Add configure-service overload for rhel based distros

- Added the start of crate writing guidelines

- add pallet.request-map/os-version

- Add specialisation for sudo for centos 5.3, to remove the -n option

- remove src/demo.clj - now in the pallet-examples basic project

- Enable script specialisation on OS version. Add os-version to Node. Add
  :os-version to image. Add a combined os-family and os-version to
  script-template.

- refactor script template generation to resource/script-template

- Add jclouds-snapshot profile.

- Add assert for non-nil request in pallet.resource/invoke-resource

- Propogate config map to request in tasks

- add explicit maven-jar-plugin version

- change lift and converge to take keyword arguments

- Updated to use template as a map, and for new Hardware in jclouds nodes

- Change maven settings keys to match jclouds


* 0.3.0

** Install

The release is on [[http://clojars.org/org.cloudhoist/pallet][clojars]].

** Known Issues

pallet.thread-expr/if-> incorrectly returns nil if there is no else expression.

pallet.main/-main goes into an infinite recursion if called without arguments.

** General

Now using [[http://jclouds.org/][jclouds]] beta 8.

There is now a node-list provider. Useful when working with a fixed set of pre-existing
nodes.

The provider credentials can now be configured in ~/.pallet/config.clj, or
by defining pallet.config/service or by setting the java system property
pallet.config.service to the qualified name of a clojure var.

The admin-user can now be configured in config.clj or project.clj, or by defining
pallet.config/admin-user.

[[https://github.com/davidsantiago/cake-pallet][Cake plugin for pallet]] from David Santiago.

The project.clj file has been removed to prevent mismatch with pom.xml

In general, support for RHEL based distros (centos, amzn-linux) should now be
much better.

** Lein and Cake tasks

The pallet-lein plugin for lein is now released to version 0.2.0.  It includes
passing of project.clj to the tasks

The command line options have changed to use the same terminology as elsewhere;
povider, identity and credential. Added blobstore-provider, blobstore-identity
and blobstore-credential options.

The `-P provider` option can be used to select the provider credentials to be used
from settings.xml or config.clj.

The task interface has changed, and now takes a first argument which is a request
map, containing :compute, :blobstore and :user keys, which are set by
pallet.main-invoker.


Added blobstore credentials.

Added containers task, to list blobstore (eg S3, CloudFiles) containers.

Added tomcat task to do simple tomcat deploy without any configuration.

Added to-blob task to enable upload of files to a blobstore.


** New Crates

squeak, etc-hosts, postgresql (thanks David Santiago)

** Enhancements

pallet.compute
  Added compute/private-ip, compute/hostname
  Abstracted jclouds usage to a protocol for improved testing

pallet.core
  ensure :target-packager is set on bootstrap

pallet.resource
  added :always-before metadata to allow resource dependencies.

pallet.resource.package
  packages now installed in single command.

pallet.resource.remote-file
  An :unpack :unzip option added

pallet.resource.file
  defines make-temp-file script function.

pallet.stevedore
  now does unquote splicing.

pallet.thread-expr
  new apply-map->

pallet.crate.etc-default
  a path can now be specified, allowing use elsewhere in the filesystem

** Fixes

pallet.resource.file
  sed will regenerate the file md5, unless :no-md5 is specified

pallet.resource.remote-file
  prevent md5 file generation when :no-versioning supplied

pallet.resource.service
  Installing init scripts with init now works on rhel based machines.

pallet.resource.stevedore
  Improved hashlib from [[https://github.com/charles-dyfis-net/pallet/commit/8e5e1df53476aedd9d32f525cf0241f8a3763269][Charles Duffy]]

pallet.resource.user
  Fix translation of :user true to -r for rhel based distros.

Java crate
  for sun java, add partner repository for ubuntu

tomcat crate
  runs on centos and amzn-linux
  fixed users database

haproxy crate
  runs on centos and amzn-linux

hudson crate
  runs on centos and amzn-linux
  fixed for case of security disabled

zookeeper crate
  now runs on centos and amzn-linux, on ec2
