#+SETUPFILE: ../org-templates/level-1.org
#+TITLE:     Reference - Providers
#+DESCRIPTION: Pallet reference documentation for providers
#+KEYWORDS: pallet providers cloud api

Pallet uses {{{jclouds}}} to create, start and stop nodes.  In order to use the cloud,
you will need to specify your cloud credentials.  Each cloud has a slightly
different terminology for the username/key and password/secret.

* Cloud Provider Names

In order to sign in to your cloud API, you will need to tell pallet the name of
your cloud.  The names pallet recognises can be displayed with the following:

#+BEGIN_SRC clojure  :session s1
   (require 'pallet.compute)
   (pallet.compute/supported-providers)
#+END_SRC

* Explicit credentials

You can log in to the cloud explicitly

#+BEGIN_SRC clojure
  (defpallet
    :serivces
      {:aws {:provider "ec2" :identity "key" :credential "secret-key"}
       :rs  {:provider "cloudservers" :identity "username" :credential "key"}})
#+END_SRC

* Credentials in settings.xml

Settings.xml is a maven file, often used to hold user specific configuration for
maven.  You can add your cloud provider information to this file, which is
normally located at [[file:~/.m2/settings.xml][~/.m2/settings.xml]].

#+BEGIN_SRC nxml
  <settings>
    <profiles>
      <profile>
        <id>terremark</id>
        <activation>
          <activeByDefault>true</activeByDefault>
        </activation>
        <properties>
          <jclouds.compute.provider>Your Cloud serivce name</jclouds.compute.provider>
          <jclouds.compute.identity>Your Cloud API username or key</jclouds.compute.identity>
          <jclouds.compute.credential>Your Cloud API secret or password</jclouds.compute.credential>
        </properties>
      </profile>
    </profiles>
  </settings>
#+END_SRC

You can then use this information with pallet:

#+BEGIN_SRC clojure  :session s1
  (require 'pallet.compute)
  (def service (pallet.compute/compute-service-from-settings))
#+END_SRC

You will need the following maven-settings dependency in your project for this
to work:

#+BEGIN_SRC nxml
    <dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-settings</artifactId>
      <version>2.0.10</version>
      <optional>true</optional>
    </dependency>
#+END_SRC

